apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openshift-gitops-operator.openshift-operators: ""
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: stable
  name: openshift-gitops-operator
  source: redhat-operator-index
  startingCSV: openshift-gitops-operator.v1.3.2
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
