---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "test-group-du"
  namespace: "test-group-pol"
spec:
  bindingRules:
    # These policies will correspond to all clusters with this label:
    test-group-du: ""
  remediationAction: enforce
  mcp: "master"
  sourceFiles:
    - fileName: PtpSubscription.yaml
      policyName: "ptp-sub-policy"
      spec:
        channel: "4.9"
    - fileName: PtpSubscriptionNS.yaml
      policyName: "ptp-sub-policy"
    - fileName: PtpSubscriptionOperGroup.yaml
      policyName: "ptp-sub-policy"
    - fileName: validatorCRs/informDuValidator.yaml
      complianceType: musthave
      remediationAction: enforce
      policyName: "du-validator-policy-sno"
    - fileName: ConsoleOperatorDisable.yaml
      policyName: "console-config-policy"
    # Log Forwarding rule
    #- fileName: ClusterLogForwarder.yaml
    #  policyName: "config-policy"
    #  spec:
    #    outputs:
    #      - type: "kafka"
    #        name: kafka-open
    #        # below url is an example
    #        url: tcp://10.46.55.190:9092/test
    #    pipelines:
    #      - name: audit-logs
    #        inputRefs:
    #         - audit
    #        outputRefs:
    #         - kafka-open
    #      - name: infrastructure-logs
    #        inputRefs:
    #         - infrastructure
    #        outputRefs:
    #         - kafka-open
    - fileName: ClusterLogging.yaml
      policyName: "clusterlog-conf-policy"
      spec:
        curation:
          curator:
            schedule: "30 3 * * *"
        collection:
          logs:
            type: "fluentd"
            fluentd: {}
    - fileName: PtpConfigSlave.yaml   # Change to PtpConfigSlaveCvl.yaml for ColumbiaVille NIC
      policyName: "ptp-conf-policy"
      metadata:
        name: "du-ptp-slave"
      spec:
        profile:
        - name: "slave"
          # This interface must match the hardware in this group
          interface: "eno12409"
          ptp4lOpts: "-2 -s --summary_interval -4"
          phc2sysOpts: "-a -r -n 24"
    - fileName: SriovOperatorConfig.yaml
      policyName: "sriov-conf-policy"
      spec:
        disableDrain: true
    - fileName: DisableSnoNetworkDiag.yaml
      policyName: "dissnonetdiag-conf-policy"
    - fileName: PerformanceProfile.yaml
      policyName: "pao-conf-policy"
      metadata:
        name: openshift-node-performance-profile
      spec:
        cpu:
          # These must be tailored for the specific hardware platform
          isolated: "2-19,22-39"
          reserved: "0-1,20-21"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 32
    - fileName: TunedPerformancePatch.yaml
      policyName: "tuned-conf-policy"
      spec:
        profile:
          - name: performance-patch
            # The 'include' line must match the PerformanceProfile metadata.name above (openshift-node-performance-${metadata.name})
            # And the cmdline_crash CPU set must match the 'isolated' set in the PerformanceProfile above
            data: |
              [main]
              summary=Configuration changes profile inherited from performance created tuned
              include=openshift-node-performance-openshift-node-performance-profile
              [bootloader]
              cmdline_crash=nohz_full=2-19,22-39
              [sysctl]
              kernel.timer_migration=1
              [service]
              service.stalld=start,enable
    - fileName: StorageLV.yaml
      policyName: "lso-conf-du-policy"
      spec:
        storageClassDevices:
          - storageClassName: "lso-sc"
            volumeMode: Block
            devicePaths:
              - /dev/nvme0n1
