apiVersion: v1
kind: Secret
metadata:
  name: bmc-secret1
  namespace: du-sno-1
data:
  password: Y2FsdmluCg==
  username: cm9vdAo=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: bmc-secret1
  namespace: du-sno-2
data:
  password: Y2FsdmluCg==
  username: cm9vdAo=
type: Opaque
