apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - site-specific-policies/test-du-lab.yaml
  - site-specific-policies/test-cu-lab.yaml
  - common-policies/test-common.yaml
  - group-policies/test-group-cu.yaml
  - group-policies/test-group-du.yaml
resources:
  - ns.yaml
  - group-policies/test-group-cu-odf.yaml
