apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: cu-compact-1
stringData:
  .dockerconfigjson: '{"auths":{"cloud.openshift.com":{"auth":"Zm9vOmJhcg==","email":"dummy@redhat.com"},"quay.io":{"auth":"Zm9vOmJhcg==","email":"dummy@redhat.com"},"registry.connect.redhat.com":{"auth":"Zm9vOmJhcg==","email":"dummy@redhat.com"},"registry.redhat.io":{"auth":"Zm9vOmJhcg==","email":"dummy@redhat.com"},"registry.test.redhat.lab:5000":{"auth":"Zm9vOmJhcg==","email":"test@example.com"}}}'
